PREFIX : <http://id.ukpds.org/schema/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX id: <http://id.ukpds.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX spin: <http://spinrdf.org/spin#>
PREFIX wikidata: <https://www.wikidata.org/wiki/>
PREFIX wikipedia: <https://en.wikipedia.org/wiki/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT {
  [] <http://www.ontotext.com/owlim/system#schemaTransaction> [] .
  
:
  a owl:Ontology;
.

:TemporalThing
	a owl:Class ;
.
:PastThing
	a owl:Class ;
	rdfs:subClassOf :TemporalThing ;
.
:MnisThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:DodsThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:UkgapThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:PimsThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:WikidataThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:WikidataParliamentPeriod
 	a owl:Class ;
  	rdfs:subClassOf :ParliamentPeriod ;
#  	rdfs:subClassOf :WikidataThing ;
.
:ExternalThing
	a owl:Class ;
.
:NamedThing
	a owl:Class ;
.
:OnsThing
	a owl:Class ;
	rdfs:subClassOf :ExternalThing ;
.
:GeographicalThing
	a owl:Class ;
.
:ContactableThing
	a owl:Class ;
.
:House
	a owl:Class ;
.
:HouseSeat
	a owl:Class ;
.
:HouseSeatType
	a owl:Class ;
.
:ConstituencyGroup
	a owl:Class ;
.
:ConstituencyArea
	a owl:Class ;
	rdfs:subClassOf :Place ;
.
:Country
	a owl:Class ;
	rdfs:subClassOf :Place ;
.
:MnisConstituencyGroup
	a owl:Class;
	rdfs:subClassOf :ConstituencyGroup ;
#	rdfs:subClassOf :MnisThing ;
.
:PastConstituencyGroup
	a owl:Class ;
	rdfs:subClassOf :ConstituencyGroup ;
#  	rdfs:subClassOf :PastThing ;
.
:SeatIncumbency
	a owl:Class ;
	rdfs:subClassOf :Incumbency ;
.
:Person
	a owl:Class ;
.
:MnisPerson
	a owl:Class ;
	rdfs:subClassOf :Person ;
#	rdfs:subClassOf :MnisThing ;
.
:DodsPerson
	a owl:Class ;
	rdfs:subClassOf :Person ;
#	rdfs:subClassOf :DodsThing ;
.
:PimsPerson
	a owl:Class ;
	rdfs:subClassOf :Person ;
#	rdfs:subClassOf :PimsThing ;
.
:DeceasedPerson
	a owl:Class;
	rdfs:subClassOf :Person ;
#	rdfs:subClassOf :PastThing ;
.
:Member
	a owl:Class ;
	rdfs:subClassOf :Person ;
#	rdfs:subClassOf :ContactableThing ; 
.
:Gender
	a owl:Class ;
.
:MnisGender
	a owl:Class ;
	rdfs:subClassOf :Gender ;
# 	rdfs:subClassOf :MnisThing ;
.
:GenderIdentity
	a owl:Class ;
.
:ContactPoint
	a owl:Class ;
.
:MnisContactPoint
	a owl:Class ;
	rdfs:subClassOf :ContactPoint ;
# 	rdfs:subClassOf :MnisThing ;
.
:PostalAddress
	a owl:Class ;
.
:Candidate
	a owl:Class ;
	rdfs:subClassOf :Person ;
.
:Candidacy
	a owl:Class ;
.
:CandidacyResult
	a owl:Class ;
.
:Party
	a owl:Class ;
.
:MnisParty
	a owl:Class ;
	rdfs:subClassOf :Party ;
#  	rdfs:subClassOf :MnisThing ;
.
:PartyMember
	a owl:Class ;
	rdfs:subClassOf :Person ;
.
:PartyMembership
	a owl:Class ;
.
:PastPartyMembership
	a owl:Class ;
	rdfs:subClassOf :PartyMembership ;
#  	rdfs:subClassOf :PastThing ;
.
:Election
	a owl:Class ;
.
:ElectionType
	a owl:Class ;
.
:MnisElectionType
	a owl:Class ;
	rdfs:subClassOf :ElectionType ;
#  	rdfs:subClassOf :MnisThing ;
.
:Electorate
	a owl:Class ;
.
:ElectoralIncumbency
	a owl:Class ;
	rdfs:subClassOf :SeatIncumbency ;
.
:ParliamentPeriod
	a owl:Class ;
.
:PastParliamentPeriod
	rdfs:subClassOf :ParliamentPeriod ;
#  	rdfs:subClassOf :PastThing ;
.	
:OnsConstituencyGroup
	a owl:Class ;
	rdfs:seeAlso <http://data.ordnancesurvey.co.uk/ontology/admingeo/WestminsterConstituency> ;
	rdfs:subClassOf :ConstituencyGroup ;
#	rdfs:subClassOf :OnsThing ;
.
:Role
	a owl:Class ;
.
:PastRole
	a owl:Class ;
	rdfs:subClassOf :Role ;
#  	rdfs:subClassOf :PastThing ;
.
:Position
	a owl:Class ;
.
:HouseIncumbency
	a owl:Class ;
	rdfs:subClassOf :Incumbency ;
	rdfs:comment "Exists to provide connection between a house member and their house where seat information is not available.  e.g. House of Lords as of 14th February 2017" ;
.
:Incumbency
	a owl:Class ;
.
:PastIncumbency
	a owl:Class;
	rdfs:subClassOf :Incumbency ;
#	rdfs:subClassOf :PastThing ;
.
:HouseIncumbencyType
	a owl:Class ;
.
:MnisHouseIncumbencyType
	a owl:Class ;
	rdfs:subClassOf :HouseIncumbencyType ;
#  	rdfs:subClassOf :MnisThing ;
.
:EPetition 
	a owl:Class ;
.
:RejectedEPetition 
	a owl:Class ;
	rdfs:subClassOf :EPetition ;

.
:ApprovedEPetition 
	a owl:Class ;
	rdfs:subClassOf :EPetition ;
	.
:UkgapEPetition 
	a owl:Class ;
	rdfs:subClassOf :EPetition ;
#  	rdfs:subClassOf :UkgapThing ;
.
:ThresholdAttainment 
	a owl:Class ;
.
:Threshold 
	a owl:Class ;
.
:Moderation 
	a owl:Class ;
.
:Debate 
	a owl:Class ;
.
:GovernmentResponse 
	a owl:Class ;
.
:LocatedSignatureCount 
	a owl:Class ;
.
:Place 
	a owl:Class ;
	rdfs:subClassOf :GeographicalThing ;
.
:Rejection 
	a owl:Class ;
	rdfs:subClassOf :Moderation ;
.
:RejectionCode 
	a owl:Class ;
.
:Approval 
	a owl:Class ;
	rdfs:subClassOf :Moderation ;
.
:ConceptualisedThing
	a owl:Class ;
.
:SubjectTaggedThing
	a owl:Class ;
.
:Concept
	rdfs:subClassOf skos:Concept ;
.
:GovRegisterThing
 	a owl:Class ;
  	rdfs:subClassOf :ExternalThing ;
.
:GovRegisterCountry
	a owl:Class;
	rdfs:subClassOf :Country ;
#	rdfs:subClassOf :GovRegisterThing ;
.
:GovRegisterTerritory
	a owl:Class;
	rdfs:subClassOf :Territory ;
#	rdfs:subClassOf :GovRegisterThing ;
.
:Territory
	a owl:Class ;
	rdfs:subClassOf :Place ;
.

##########################OBJECT PROPERTIES##############################

:houseSeatHasHouse
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :HouseSeat ;
	rdfs:range :House ;
.
:houseHasHouseSeat
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :houseSeatHasHouse ;
	rdfs:domain :House ;
	rdfs:range :HouseSeat ;
.
:houseSeatHasConstituencyGroup
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :HouseSeat ;
	rdfs:range :ConstituencyGroup ;
.
:constituencyGroupHasHouseSeat
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :houseSeatHasConstituencyGroup ;
	rdfs:domain :ConstituencyGroup ;
	rdfs:range :HouseSeat ;
.
:houseSeatHasHouseSeatType
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :HouseSeat ;
	rdfs:range :HouseSeatType ;
.
:houseSeatTypeHasHouseSeat
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :houseSeatHasHouseSeatType ;
	rdfs:domain :HouseSeatType ;
	rdfs:range :HouseSeat ;
.
:seatIncumbencyHasHouseSeat
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :SeatIncumbency ;
	rdfs:range :HouseSeat ;
.
:houseSeatHasSeatIncumbency
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :seatIncumbencyHasHouseSeat ;
	rdfs:domain :HouseSeat ;
	rdfs:range :SeatIncumbency ;
.
:parliamentPeriodHasImmediatelyPreviousParliamentPeriod
	a owl:ObjectProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty ;
	rdfs:domain :ParliamentPeriod ;
	rdfs:range :ParliamentPeriod ;
.
:parliamentPeriodHasImmediatelyFollowingParliamentPeriod
	a owl:ObjectProperty ;
	owl:inverseOf :parliamentPeriodHasImmediatelyPreviousParliamentPeriod ;
	rdfs:domain :ParliamentPeriod ;
	rdfs:range :ParliamentPeriod ;
.
:seatIncumbencyHasParliamentPeriod
	a owl:ObjectProperty ;
	rdfs:domain :SeatIncumbency ;
	rdfs:range :ParliamentPeriod ;
.
:parliamentPeriodHasSeatIncumbency
	a owl:ObjectProperty ;
	owl:inverseOf :seatIncumbencyHasParliamentPeriod ;
	rdfs:domain :ParliamentPeriod ;
	rdfs:range :SeatIncumbency ;
.
:incumbencyHasMember
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Incumbency ;
	rdfs:range :Member ;
.
:memberHasIncumbency
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :incumbencyHasMember ;
	rdfs:domain :Member ;
	rdfs:range :Incumbency ;
.
:genderIdentityHasPerson
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :GenderIdentity ;
	rdfs:range :Person ;
.
:personHasGenderIdentity
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :genderIdentityHasPerson ;
	rdfs:domain :Person ;
	rdfs:range :GenderIdentity ;
.
:genderIdentityHasGender
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :GenderIdentity ;
	rdfs:range :Gender ;
.
:genderHasGenderIdentity
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :genderIdentityHasGender ;
	rdfs:domain :Gender ;
	rdfs:range :GenderIdentity ;
.
:contactableThingHasContactPoint
	a owl:ObjectProperty ;
	rdfs:domain :ContactableThing ;
	rdfs:range :ContactPoint ;
.
:contactPointHasContactableThing
	owl:inverseOf :contactableThingHasContactPoint ;
	rdfs:domain :ContactPoint ;
	rdfs:range :ContactableThing ;
.
:contactPointHasPostalAddress
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :ContactPoint ;
	rdfs:range :PostalAddress ;
.
:postalAddressHasContactPoint
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :contactPointHasPostalAddress ;
	rdfs:domain :PostalAddress ;
	rdfs:range :ContactPoint ;
.
:partyMembershipHasPartyMember
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :PartyMembership ;
	rdfs:range :PartyMember ;
.
:partyMemberHasPartyMembership
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :partyMembershipHasPartyMember ;
	rdfs:domain :PartyMember ;
	rdfs:range :PartyMembership ;
.
:partyMembershipHasParty
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :PartyMembership ;
	rdfs:range :Party ;
.
:partyHasPartyMembership
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :partyMembershipHasParty ;
	rdfs:domain :Party ;
	rdfs:range :PartyMembership ;
.
:candidacyHasCandidate
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Candidacy ;
	rdfs:range :Candidate ;
.
:candidateHasCandidacy
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :candidacyHasCandidate ;
	rdfs:domain :Candidate ;
	rdfs:range :Candidacy ;
.
:candidacyHasParty
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Candidacy ;
	rdfs:range :Party ;
.
:partyhasCandidacy
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :candidacyHasParty ;
	rdfs:domain :Party ;
	rdfs:range :Candidacy ;
.
:candidacyHasCandidacyResult
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Candidacy ;
	rdfs:range :CandidacyResult ;
.
:candidacyResultHasCandidacy
	a owl:ObjectProperty, owl:FunctionalProperty ;
	owl:inverseOf :candidacyHasCandidacyResult ;
	rdfs:domain :CandidacyResult ;
	rdfs:range :Candidacy ;
.
:candidacyHasElection
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Candidacy ;
	rdfs:range :Election ;
.
:electionHasCandidacy
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :candidacyHasElection ;
	rdfs:domain :Election ;
	rdfs:range :Candidacy ;
.
:electionHasElectorate
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Election ;
	rdfs:range :Electorate ;
.
:electorateHasElection
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :electionHasElectorate ;
	rdfs:domain :Electorate ;
	rdfs:range :Election ;
.
:electionHasElectionType
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Election ;
	rdfs:range :ElectionType ;
.
:electionTypeHasElection
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :electionHasElectionType ;
	rdfs:domain :ElectionType ;
	rdfs:range :Election ;
.
:electorateHasConstitutencyGroup
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Electorate ;
	rdfs:range :ConstituencyGroup ;
.
:constituencyGroupHasElectorate
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :electorateHasConstitutencyGroup ;
	rdfs:domain :ConstituencyGroup ;
	rdfs:range :Electorate ;
.
:electoralIncumbencyHasCandidacyResult
	a owl:ObjectProperty, owl:FunctionalProperty  ;
	rdfs:domain :ElectoralIncumbency ;
	rdfs:range :CandidacyResult ;
.
:candidacyResultHasElectoralIncumbency
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :electoralIncumbencyHasCandidacyResult ;
	rdfs:domain :CandidacyResult ;
	rdfs:range :ElectoralIncumbency ;
.
:constituencyGroupHasConstituencyArea
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyGroup ;
	rdfs:range :ConstituencyArea ;
.
:constituencyAreaHasConstituencyGroup
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :constituencyGroupHasConstituencyArea ;
	rdfs:domain :ConstituencyArea ;
	rdfs:range :ConstituencyGroup ;
.
:incumbencyHasContactPoint
	a owl:ObjectProperty ;
	rdfs:subPropertyOf :contactableThingHasContactPoint ;
	rdfs:domain :Incumbency ;
	rdfs:range :ContactPoint ;
.
:contactPointHasIncumbency
	a owl:ObjectProperty ;
	owl:inverseOf :incumbencyHasContactPoint ;
	rdfs:domain :ContactPoint ;
	rdfs:range :Incumbency ;
.
:electoralIncumbencyHasContactPoint
	a owl:ObjectProperty ;
	rdfs:subPropertyOf :contactableThingHasContactPoint ;
	rdfs:domain :ElectoralIncumbency ;
	rdfs:range :ContactPoint ;
.
:contactPointHasElectoralIncumbency
	a owl:ObjectProperty ;
	owl:inverseOf :electoralIncumbencyHasContactPoint ;
	rdfs:domain :ContactPoint ;
	rdfs:range :ElectoralIncumbency ;
.
:personHasContactPoint
	rdfs:subPropertyOf :contactableThingHasContactPoint ;
	a owl:ObjectProperty ;
	rdfs:domain :Person ;
	rdfs:range :ContactPoint ;
.
:contactPointHasPerson
	a owl:ObjectProperty ;
	owl:inverseOf :personHasContactPoint ;
	rdfs:domain :ContactPoint ;
	rdfs:range :Person ;
.
:personHasRole
	a owl:ObjectProperty ;
	rdfs:domain :Person ;
	rdfs:range :Role ;
.
:roleHasPerson
	owl:inverseOf :personHasRole ;
	rdfs:domain :Role ;
	rdfs:range :Person ;
.
:positionHasRole
	a owl:ObjectProperty ;
	rdfs:domain :Position ;
	rdfs:range :Role ;
.
:roleHasPosition
	owl:inverseOf :positionHasRole ;
	rdfs:domain :Role ;
	rdfs:range :Position ;
.
:houseIncumbencyHasHouseIncumbencyType
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :HouseIncumbency ;
	rdfs:range :HouseIncumbencyType ;
.
:houseIncumbencyTypeHasHouseIncumbency
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :houseIncumbencyHasHouseIncumbencyType ;
	rdfs:domain :HouseIncumbencyType ;
	rdfs:range :HouseIncumbency ;
.
:houseIncumbencyHasHouse
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :HouseIncumbency ;
	rdfs:range :House ;
.
:houseHasHouseIncumbency
	a owl:InverseFunctionalProperty ;
	owl:inverseOf :houseIncumbencyHasHouse ;
	rdfs:domain :House ;
	rdfs:range :HouseIncumbency ;
.
:conceptualisedThingHasConcept
	a owl:ObjectProperty ; 
	rdfs:subPropertyOf foaf:focus ;
	rdfs:domain :ConceptualisedThing ;
	rdfs:range :Concept ;
.
:conceptHasConceptualisedThing
	owl:inverseOf :conceptualisedThingHasConcept; 
	rdfs:domain :Concept ;
	rdfs:range :ConceptualisedThing ;
.
:subjectTaggedThingHasConcept
	a owl:ObjectProperty ; 
	rdfs:subPropertyOf dcterms:subject ;
	rdfs:domain :SubjectTaggedThing ;
	rdfs:range :Concept ;
.
:conceptHasSubjectTaggedThing
	owl:inverseOf :subjectTaggedThingHasConcept; 
	rdfs:domain :Concept ;
	rdfs:range :SubjectTaggedThing ;
.
:ePetitionHasThresholdAttainment 
	a owl:ObjectProperty, owl:InverseFunctionalProperty ;
	rdfs:domain :EPetition ;
	rdfs:range :ThresholdAttainment ;
.
:thresholdAttainmentHasEPetition 
	owl:inverseOf :ePetitionHasThresholdAttainment ;
	rdfs:domain :ThresholdAttainment ;
	rdfs:range :EPetition ;
.
:thresholdAttainmentHasThreshold 
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :ThresholdAttainment ;
	rdfs:range :Threshold ;
.
:thresholdHasThresholdAttainment 
	owl:inverseOf :thresholdAttainmentHasThreshold ;
	rdfs:domain :Threshold ;
	rdfs:range :ThresholdAttainment ;
.
:ePetitionHasDebate 
	a owl:ObjectProperty ;
	rdfs:domain :EPetition ;
	rdfs:range :Debate ;
.
:debateHasEPetition 
	owl:inverseOf :ePetitionHasDebate ;
	rdfs:domain :Debate ;
	rdfs:range :EPetition ;
.
:ePetitionHasGovernmentResponse 
	a owl:ObjectProperty ;
	rdfs:domain :EPetition ;
	rdfs:range :GovernmentResponse ;
.
:governmentResponseHasEPetition 
	owl:inverseOf :ePetitionHasGovernmentResponse ;
	rdfs:domain :GovernmentResponse ;
	rdfs:range :EPetition ;
.
:ePetitionHasModeration 
	a owl:ObjectProperty, owl:InverseFunctionalProperty ;
	rdfs:domain :EPetition ;
	rdfs:range :Moderation ;
.
:moderationHasEPetition
	owl:inverseOf :ePetitionHasModeration ;
	rdfs:domain :Moderation ;
	rdfs:range :EPetition ;
.
:rejectedEPetitionHasRejection 
	a owl:ObjectProperty, owl:InverseFunctionalProperty ;
	rdfs:subPropertyOf :ePetitionHasModeration ;
	rdfs:domain :RejectedEPetition ;
	rdfs:range :Rejection ;
.
:rejectionHasRejectedEPetition 
	owl:inverseOf :rejectedEPetitionHasRejection ;
	rdfs:subPropertyOf :moderationHasEPetition ;
	rdfs:domain :Rejection ;
	rdfs:range :RejectedEPetition ;
.
:approvedEPetitionHasApproval 
	a owl:ObjectProperty, owl:InverseFunctionalProperty ;
	rdfs:subPropertyOf :ePetitionHasModeration ;
	rdfs:domain :ApprovedEPetition ;
	rdfs:range :Approval ;
.
:approvalHasApprovedEPetition 
	owl:inverseOf :approvedEPetitionHasApproval ;
	rdfs:subPropertyOf :moderationHasEPetition ;
	rdfs:domain :Approval ;
	rdfs:range :ApprovedEPetition ;
.
:ePetitionHasLocatedSignatureCount 
	a owl:ObjectProperty, owl:InverseFunctionalProperty ;
	rdfs:domain :EPetition ;
	rdfs:range :LocatedSignatureCount ;
.
:locatedSignatureCountHasEPetition 
	owl:inverseOf :ePetitionHasLocatedSignatureCount; 
	rdfs:domain :LocatedSignatureCount ;
	rdfs:range :EPetition ;
.
:locatedSignatureCountHasPlace 
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :LocatedSignatureCount ;
	rdfs:range :Place ;
.
:placeHasLocatedSignatureCount
	owl:inverseOf :locatedSignatureCountHasPlace; 
	rdfs:domain :Place ;
	rdfs:range :LocatedSignatureCount ;
.
:containedByPlace 
	rdf:type owl:ObjectProperty ;
	rdfs:comment "Relates a place to a place it is contained by e.g. town in constituency in county in country."@en ;
	rdfs:domain :Place ;
	rdfs:range :Place ;
.	
:containsPlace 
	owl:inverseOf :containedByPlace; 
	rdfs:comment "Relates a place to a place it contains by e.g. country contains constituency contains town."@en ;
	rdfs:domain :Place ;
	rdfs:range :Place ;
.
:constituencyAreaHasCountry
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :containedByPlace ;
	rdfs:domain :ConstituencyArea ;
	rdfs:range :Country ;
.
:countryHasConstituencyArea
	owl:inverseOf :constituencyAreaHasCountry ; 
	rdfs:subPropertyOf :containsPlace ;
	rdfs:domain :Country ;
	rdfs:range :ConstituencyArea ;
.
:rejectionHasRejectionCode
	a owl:ObjectProperty, owl:FunctionalProperty ;
	rdfs:domain :Rejection ;
	rdfs:range :RejectionCode ;	
.
:rejectionCodeHasRejection
	owl:inverseOf :rejectionHasRejectionCode ; 
	rdfs:domain :RejectionCode ;
	rdfs:range :Rejection ;	
.

########################DATATYPE PROPERTIES##############################


:incumbencyStartDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :startDate ;
	rdfs:domain :Incumbency ;
	rdfs:range xsd:date ;
.
:startDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :TemporalThing ;
	rdfs:range xsd:date ;
.
:endDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PastThing ;
	rdfs:range xsd:date ;
	rdfs:comment "By convention, endDate is only used after the date." ;
.
:personDateOfBirth
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :startDate ;
	rdfs:domain :Person ;
	rdfs:range xsd:date ;
.
:personDateOfDeath
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :endDate ;
	rdfs:domain :DeceasedPerson ;
	rdfs:range xsd:date ;
.
:externalIdentifier
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ExternalThing ;
	rdfs:range xsd:string ;
.
:mnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :MnisThing ;
	rdfs:range xsd:string ;
.
:personMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :mnisId ;
	rdfs:domain :MnisPerson ;
	rdfs:range xsd:string ;
.
:constituencyGroupMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :mnisId ;
	rdfs:domain :MnisConstituencyGroup ;
	rdfs:range xsd:string ;
.
:pimsId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :PimsThing ;
	rdfs:range xsd:string ;
.
:wikidataId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :WikidataThing ;
	rdfs:range xsd:string ;
.
:parliamentPeriodWikidataId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :wikidataId ;
	rdfs:domain :WikidataParliamentPeriod ;
	rdfs:range xsd:string ;
.
:dodsId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :DodsThing ;
	rdfs:range xsd:string ;
.
:ukgapId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :UkgapThing ;
	rdfs:range xsd:string ;
.
:personPimsId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :pimsId ;
	rdfs:domain :PimsPerson ;
	rdfs:range xsd:string ;
.
:personDodsId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :dodsId ;
	rdfs:domain :DodsPerson ;
	rdfs:range xsd:string ;
.
:ePetitionUkgapId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :ukgapId ;
	rdfs:domain :UkgapEPetition ;
	rdfs:range xsd:string ;
.
:personFamilyName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Person ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:personGivenName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Person ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:personOtherNames
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Person ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:addressLine1
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ;
.
:addressLine2
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ;
.
:addressLine3
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ;
.
:addressLine4
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ;
.
:addressLine5
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ; 
.
:postCode
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PostalAddress ;
	rdfs:range xsd:string ;
.
:faxNumber
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ContactPoint ;
	rdfs:range xsd:string ;
.
:email
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ContactPoint ;
	rdfs:range xsd:string ;
.
:phoneNumber
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ContactPoint ;
	rdfs:range xsd:string ;
.
:contactForm
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ContactPoint ;
	rdfs:range xsd:string ;
.
:voteCount
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :CandidacyResult ;
	rdfs:range xsd:integer ;
.
:resultPosition
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :CandidacyResult ;
	rdfs:range xsd:integer ;
.
:constituencyGroupEndDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PastConstituencyGroup ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :endDate ;
.
:constituencyAreaExtent
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyArea ;
	rdfs:range geosparql:wktLiteral ; 
	rdfs:seeAlso schema:polygon ;
.
geosparql:wktLiteral
	a rdfs:Datatype ;
.
:constituencyAreaLatitude
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyArea ;
	rdfs:subPropertyOf :latitude ;
.
:constituencyAreaLongitude
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyArea ;
	rdfs:subPropertyOf :longitude ;
.
:constituencyGroupOnsCode
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :onsCode ;
	rdfs:domain :OnsConstituencyGroup ;
	rdfs:range xsd:string ;
.
:onsCode
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :OnsThing ;
	rdfs:range xsd:string ;
.
:constituencyGroupStartDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyGroup ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :startDate ;
.
:contactPointMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :MnisContactPoint ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :mnisId ;
.
:latitude
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :GeographicalThing ;
	rdfs:range xsd:decimal ;
.
:longitude
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :GeographicalThing ;
	rdfs:range xsd:decimal ;
.
:partyMembershipStartDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PartyMembership ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :startDate ;
.
:partyMembershipEndDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PastPartyMembership ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :endDate ;
.
:partyMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :MnisParty ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :mnisId ;
.
:electionTypeMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :MnisElectionType ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :mnisId ;
.
:name
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :NamedThing ;
	rdfs:range xsd:string ;
  	rdfs:subPropertyOf rdfs:label ;
.
:partyName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Party ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:houseName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :House ;
	rdfs:range xsd:string ;
.
:houseSeatName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :HouseSeat ;
	rdfs:range xsd:string ;
.
:houseSeatTypeName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :HouseSeatType ;
	rdfs:range xsd:string ;
.
:genderName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Gender ;
	rdfs:range xsd:string ;
.
:genderMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :MnisGender ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :mnisId ;
.
:electionName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Election ;
	rdfs:range xsd:string ;
.
:electionTypeName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :ElectionType ;
	rdfs:range xsd:string ;
.
:constituencyGroupName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ConstituencyGroup ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:positionName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Position ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :name ;
.
:roleStartDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Role ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :startDate ;
.
:roleEndDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PastRole ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :endDate ;
.
:parliamentPeriodStartDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ParliamentPeriod ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :startDate ;
.
:parliamentPeriodEndDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :PastParliamentPeriod ;
	rdfs:range xsd:date ;
	rdfs:subPropertyOf :endDate ;
.
:parliamentPeriodNumber
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ParliamentPeriod ;
	rdfs:range xsd:integer ;
.
:thresholdAttainmentAt 
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :ThresholdAttainment ;
	rdfs:range xsd:dateTime ;
.
:action 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:string ;
.
:background 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:string ;
.
:additionalDetails 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:string ;
.
:createdAt 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:dateTime ;
.
:updatedAt 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:dateTime ;
.
:closedAt 
	a owl:DatatypeProperty ;
	rdfs:domain :EPetition ;
	rdfs:range xsd:dateTime ;
.
:signatureCount 
	a owl:DatatypeProperty ;
	rdfs:domain :LocatedSignatureCount ;
	rdfs:range xsd:integer ;
.
:signatureCountRetrievedAt 
	a owl:DatatypeProperty ;
	rdfs:domain :LocatedSignatureCount ;
	rdfs:range xsd:dateTime ;
.
:thresholdName
	a owl:DatatypeProperty ;
	rdfs:domain :Threshold ;
	rdfs:range xsd:string ;
.	
:thresholdSignatureNumber
	a owl:DatatypeProperty ;
	rdfs:domain :Threshold ;
	rdfs:range xsd:integer ;
.
:governmentResponseSummary
	a owl:DatatypeProperty ;
	rdfs:domain :GovernmentResponse ;
	rdfs:range xsd:string ;
.
:governmentResponseDetails
	a owl:DatatypeProperty ;
	rdfs:domain :GovernmentResponse ;
	rdfs:range xsd:string ;
.
:governmentResponseCreatedAt
	a owl:DatatypeProperty ;
	rdfs:domain :GovernmentResponse ;
	rdfs:range xsd:dateTime ;
.
:governmentResponseUpdatedAt
	a owl:DatatypeProperty ;
	rdfs:domain :GovernmentResponse ;
	rdfs:range xsd:dateTime ;
.
:moderatedAt
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :Moderation ;
	rdfs:range xsd:dateTime ;
.
:approvedAt
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :moderatedAt ;
	rdfs:domain :Approval ;
	rdfs:range xsd:dateTime ;
.
:rejectedAt
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :moderatedAt ;
	rdfs:domain :Rejection ;
	rdfs:range xsd:dateTime ;
.
:rejectionDetails
	a owl:DatatypeProperty ;
	rdfs:domain :Rejection ;
	rdfs:range xsd:string ;
.
#:rejectionName
#	a owl:DatatypeProperty ;
#	rdfs:domain :Rejection ;
#	rdfs:range xsd:string ;
#.
:rejectionCodeName
	a owl:DatatypeProperty ;
	rdfs:domain :RejectionCode ;
	rdfs:range xsd:string ;
.
:debateDate
	a owl:DatatypeProperty ;
	rdfs:domain :Debate ;
	rdfs:range xsd:date ;
.
:debateProposedDate
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :proposedStartDate ;
	rdfs:domain :Debate ;
	rdfs:range xsd:date ;
.
:debateTranscriptUrl
	a owl:DatatypeProperty ;
	rdfs:domain :Debate ;
	rdfs:range xsd:string ;
.
:debateVideoUrl
	a owl:DatatypeProperty ;
	rdfs:domain :Debate ;
	rdfs:range xsd:string ;
.
:debateOverview
	a owl:DatatypeProperty ;
	rdfs:domain :Debate ;
	rdfs:range xsd:string ;
.		
:proposedStartDate
	a owl:DatatypeProperty ;
	rdfs:domain owl:Thing ;
	rdfs:range xsd:date ;	
.
:proposedEndDate
	a owl:DatatypeProperty ;
	rdfs:domain owl:Thing ;
	rdfs:range xsd:date ;	
.
:incumbencyEndDate
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :endDate ;
	rdfs:domain :PastIncumbency ;
	rdfs:range xsd:date ;
.
:houseIncumbencyTypeName
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :HouseIncumbencyType ;
	rdfs:range xsd:string ;
.
:houseIncumbencyTypeMnisId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:domain :MnisHouseIncumbencyType ;
	rdfs:range xsd:string ;
	rdfs:subPropertyOf :mnisId ;
.
:govRegisterId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :externalIdentifier ;
	rdfs:domain :GovRegisterThing ;
	rdfs:range xsd:string ;
.
:countryGovRegisterId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :govRegisterId ;
	rdfs:domain :GovRegisterCountry ;
	rdfs:range xsd:string ;
.
:countryName
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Country ;
	rdfs:range xsd:string ;
.
:countryOfficialName
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Country ;
	rdfs:range xsd:string ;
.
:countryCitizenNames
	a owl:DatatypeProperty ;
	rdfs:domain :Country ;
	rdfs:range xsd:string ;
.
:govRegisterCountryStartDate
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :startDate ;
	rdfs:domain :GovRegisterCountry ;
	rdfs:range xsd:date ;
.
:govRegisterCountryEndDate
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :endDate ;
	rdfs:domain :GovRegisterCountry ;
	rdfs:range xsd:date ;
.
:territoryGovRegisterId
	a owl:DatatypeProperty, owl:FunctionalProperty ;
	rdfs:subPropertyOf :govRegisterId ;
	rdfs:domain :GovRegisterTerritory ;
	rdfs:range xsd:string ;
.
:territoryName
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Territory ;
	rdfs:range xsd:string ;
.
:territoryOfficialName
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :name ;
	rdfs:domain :Territory ;
	rdfs:range xsd:string ;
.
:govRegisterTerritoryStartDate
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :startDate ;
	rdfs:domain :GovRegisterTerritory ;
	rdfs:range xsd:date ;
.
:govRegisterTerritoryEndDate
	a owl:DatatypeProperty ;
	rdfs:subPropertyOf :endDate ;
	rdfs:domain :GovRegisterTerritory ;
	rdfs:range xsd:date ;
.


 	:WikidataParliamentPeriod rdfs:subClassOf :WikidataThing .
	:MnisConstituencyGroup	rdfs:subClassOf :MnisThing .
	:PastConstituencyGroup rdfs:subClassOf :PastThing .
 	:MnisPerson rdfs:subClassOf :MnisThing .
 	:DodsPerson rdfs:subClassOf :DodsThing .
	:PimsPerson rdfs:subClassOf :PimsThing .
	:DeceasedPerson rdfs:subClassOf :PastThing .
	:Member rdfs:subClassOf :ContactableThing .
	:MnisGender rdfs:subClassOf :MnisThing .
 	:MnisContactPoint rdfs:subClassOf :MnisThing .
	:MnisParty rdfs:subClassOf :MnisThing .
	:PastPartyMembership rdfs:subClassOf :PastThing .
	:MnisElectionType rdfs:subClassOf :MnisThing .
	:PastParliamentPeriod rdfs:subClassOf :PastThing .	
	:OnsConstituencyGroup rdfs:subClassOf :OnsThing .
	:PastRole rdfs:subClassOf :PastThing .
	:PastIncumbency rdfs:subClassOf :PastThing .
	:MnisHouseIncumbencyType rdfs:subClassOf :MnisThing .
	:UkgapEPetition rdfs:subClassOf :UkgapThing .
	:GovRegisterCountry	rdfs:subClassOf :GovRegisterThing .
	:GovRegisterTerritory rdfs:subClassOf :GovRegisterThing .

}
WHERE { }